#!/usr/bin/env python3

import rospy
from action.action_server import MoveBotActionServer

if __name__ == '__main__':
    try:
        server = MoveBotActionServer()
    except rospy.ROSInterruptException:
        rospy.loginfo("Action terminated.")