#!/usr/bin/env python3


import rospy
from service.service_server import ServiceServer

if __name__ == '__main__':
    try:
        server = ServiceServer()
    except rospy.ROSInterruptException:
        rospy.loginfo("Action terminated.")