#!/usr/bin/env python3


import rospy
from service.service_client import ServiceClient

if __name__ == '__main__':
    try:
        client = ServiceClient()
    except rospy.ROSInterruptException:
        rospy.loginfo("Action terminated.")